config/routes.rb
Rails.application.routes.draw do
  resources :bookinfos

  resources :books

  resources :categories

  resources :posts

  get 'catwork' => 'categories#startWorking'
  get 'bookwork' => 'categories#startbookCrawl'
  get 'bookinfowork' => 'books#bookinfocrawl'
  get 'csv' => 'bookinfos#download_csv'
  get 'bookcount' => 'bookinfos#bookcount'

  get 'search' => 'bookinfos#search'

  mount Resque::Server, :at => "/resque"

  root 'bookinfos#index'

end

app/models/bookinfo.rb
require 'bookinfocrawl'
require 'bookinfocrawljob'
require 'csv'

class Bookinfo
  include Mongoid::Document
  field :title, type: String
  field :pid, type: String
  field :price, type: String
  field :categories, type: String
  field :author, type: String
  field :metadata, type: Hash
  field :url, type: String
  field :mainimg, type: String
  field :imgs, type: Array
  field :html, type:String

  # validates :pid, uniqueness: true


  def self.to_csv(options = {})
    column_names = Bookinfo.first.attributes.keys
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |product|
        csv << product.attributes.values_at(*column_names)
      end
    end
  end

  def self.search(q)

    results = Bookinfo.where(:title => /#{q}/i)
    results += Bookinfo.where('metadata.ISBN-10' => /#{q}/i)
    results += Bookinfo.where('metadata.ISBN-13' => /#{q}/i)
    results += Bookinfo.where('author' => /#{q}/i)

    results

  end

  def self.removeDuplicates
    
    pids = Hash.new
    
    Bookinfo.all.each{ |b|
      
      if pids.has_key? b.pid
        
        puts "Duplicate Found: #{b.title}"
        b.delete

      else

        pids[b.pid] = true

      end
      
    }

  end

  def self.getAndSaveBookInfo(url)

    bc = BookInfoCrawl.new url

    bookData = bc.getBookInfo

    Resque.enqueue(BookInfoSaveDbJob, bookData)

  end

  def self.saveBookDataToDb(bookData)
    
    Bookinfo.create(bookData)

  end

end

app/controllers/bookinfos_controller.rb
class BookinfosController < ApplicationController
  before_action :set_bookinfo, only: [:show, :edit, :update, :destroy]

  # GET /bookinfos
  # GET /bookinfos.json
  def index
    require 'will_paginate/array'
    @bookinfos = Bookinfo.all.limit(100).paginate(:page => params[:page], :limit => 15)

    require 'csv'
    respond_to do |format|
      format.html
      format.csv { 
        @bookinfos = Bookinfo.all
        send_data @bookinfos.to_csv }
      format.xls { 
        @bookinfos = Bookinfo.all
        send_data @bookinfos.to_csv(col_sep: "\t") }

    end

  end

  def bookcount
    
    render :text => Bookinfo.count
  end

  def search

    require 'will_paginate/array'
    @bookinfos = Bookinfo.search(params[:q]).paginate(:page => params[:page], :limit => 10)

    render "index"
    
  end

  def download_csv

    @bookinfos = Bookinfo.all.limit(10)

    require 'csv'

    send_data @bookinfos.to_csv

  end

  # GET /bookinfos/1
  # GET /bookinfos/1.json
  def show
  end

  # GET /bookinfos/new
  def new
    @bookinfo = Bookinfo.new
  end

  # GET /bookinfos/1/edit
  def edit
  end

  # POST /bookinfos
  # POST /bookinfos.json
  def create
    @bookinfo = Bookinfo.new(bookinfo_params)

    respond_to do |format|
      if @bookinfo.save
        format.html { redirect_to @bookinfo, notice: 'Bookinfo was successfully created.' }
        format.json { render :show, status: :created, location: @bookinfo }
      else
        format.html { render :new }
        format.json { render json: @bookinfo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookinfos/1
  # PATCH/PUT /bookinfos/1.json
  def update
    respond_to do |format|
      if @bookinfo.update(bookinfo_params)
        format.html { redirect_to @bookinfo, notice: 'Bookinfo was successfully updated.' }
        format.json { render :show, status: :ok, location: @bookinfo }
      else
        format.html { render :edit }
        format.json { render json: @bookinfo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookinfos/1
  # DELETE /bookinfos/1.json
  def destroy
    @bookinfo.destroy
    respond_to do |format|
      format.html { redirect_to bookinfos_url, notice: 'Bookinfo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bookinfo
      @bookinfo = Bookinfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bookinfo_params
      params.require(:bookinfo).permit(:title, :pid, :price, :categories, :author, :metadata, :url, :mainimg, :imgs)
    end
end

app/helpers/bookinfos_helper.rb
module BookinfosHelper
end

app/views/bookinfos/_form.html.erb
<%= form_for(@bookinfo, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @bookinfo.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@bookinfo.errors.count, "error") %> prohibited this bookinfo from being saved:</h4>

      <ul>
      <% @bookinfo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :pid, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :pid, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :price, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :price, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :categories, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :categories, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :author, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :author, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :metadata, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :metadata, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :url, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :url, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :mainimg, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :mainimg, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :imgs, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :imgs, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/bookinfos/edit.html.erb
<div class="page-header">
  <%= link_to bookinfos_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @bookinfo, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing bookinfo</h1>
</div>

<%= render 'form' %>

app/views/bookinfos/index.html.erb
<div class="page-header">
  <%# <%= link_to new_bookinfo_path, :class => 'btn btn-primary' do %>
  <%#   <span class="glyphicon glyphicon-plus"></span>
  <%#   New Bookinfo
  <%# <% end %>
  <%= link_to "Download Excel (xls)", bookinfos_path(format: "xls"), :class =>'btn btn-primary' %>
  <h1>Listing <span id="bcount"><%= Bookinfo.count %></span> bookinfos</h1>
</div>
<form action="/search" id="searchForm" >
  <input name="q" type="text" class="form-control" placeholder="Search for book title or ISBN">
</form>

 <%= will_paginate @bookinfos %>
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Cover</th>
            <th>Title</th>
            <th>ISBN-10</th>
            <th>ISBN-13</th>
            <th>Price</th>
            <th>Categories</th>
            <th>Author</th>
            <th>Metadata</th>
            <th>Pid</th>
            <th>Url</th>
            <th>Imgs</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @bookinfos) do |bookinfo| %>
        <td><%= image_tag bookinfo.mainimg , :class => 'coverpic' %></td>
            <td><%= bookinfo.title %></td>
            <td><%= bookinfo.metadata['ISBN-10'] %></td>
            <td><%= bookinfo.metadata['ISBN-13'] %></td>
            <td><%= bookinfo.price %></td>
            <td><%= bookinfo.categories %></td>
            <td><%= bookinfo.author %></td>
            <td><%= bookinfo.metadata %></td>
            <td><%= bookinfo.pid %></td>

            <td><%= bookinfo.url %></td>
            <!-- <td><%= bookinfo.mainimg %></td> -->
            <td><%= bookinfo.imgs %></td>
            <td><%= link_to 'Show', bookinfo %></td>
        <td><%= link_to 'Edit', edit_bookinfo_path(bookinfo) %></td>
        <td><%= link_to 'Destroy', bookinfo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>
 <%= will_paginate @bookinfos %>

 <script>

function getBookcountrec(){
    // do whatever you like here

    getBookcount();

    setTimeout( getBookcountrec, 2000);
}
// getBookcountrec();
 </script>

app/views/bookinfos/new.html.erb
<div class="page-header">
  <%= link_to bookinfos_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New bookinfo</h1>
</div>

<%= render 'form' %>

app/views/bookinfos/show.html.erb
<div class="page-header">
  <%= link_to bookinfos_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_bookinfo_path(@bookinfo), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show bookinfo</h1>
</div>

<dl class="dl-horizontal">
  <dt>Title:</dt>
  <dd><%= @bookinfo.title %></dd>

  <dt>Pid:</dt>
  <dd><%= @bookinfo.pid %></dd>

  <dt>Price:</dt>
  <dd><%= @bookinfo.price %></dd>

  <dt>Categories:</dt>
  <dd><%= @bookinfo.categories %></dd>

  <dt>Author:</dt>
  <dd><%= @bookinfo.author %></dd>

  <dt>Metadata:</dt>
  <dd><%= @bookinfo.metadata %></dd>

  <dt>Url:</dt>
  <dd><%= @bookinfo.url %></dd>

  <dt>Mainimg:</dt>
  <dd><%= @bookinfo.mainimg %></dd>

  <dt>Imgs:</dt>
  <dd><%= @bookinfo.imgs %></dd>

</dl>